# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRuTduakBGt50VKxxvx7IbSrkC9AWqKj
"""

import streamlit as st
import onnxruntime
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import os

# --- Configuration ---
LOCAL_ONNX_MODEL_PATH = "best.onnx"

# Class names (from your data.yaml)
CLASS_NAMES = ['BJT-NPN', 'BJT-PNP', 'Capacitor', 'Diode', 'GND', 'I-AC', 'I-DC', 'Inductor', 'MOSFET-N', 'MOSFET-P', 'Op-Amp', 'Resistor', 'V-AC', 'V-DC', 'V-DC (one port)', 'Wire Crossover', 'Zener Diode']

# Model input size
IMG_SIZE = (640, 640)

# --- Model Loading ---
@st.cache_resource
def load_model():
    if not os.path.exists(LOCAL_ONNX_MODEL_PATH):
        # Model is expected to be in the repo, if it's not found,
        # then there's an issue with the deployment or file placement.
        st.error(f"ONNX model '{LOCAL_ONNX_MODEL_PATH}' not found locally. Please ensure it's in the same directory as app.py.")
        return None

    try:
        session = onnxruntime.InferenceSession(LOCAL_ONNX_MODEL_PATH)
        st.success("ONNX model loaded successfully!")
        return session
    except Exception as e:
        st.error(f"Error loading ONNX model: {e}")
        return None

session = load_model()

# --- Preprocessing Function ---
def preprocess_image(image: Image.Image):
    img_resized = image.resize(IMG_SIZE)
    img_np = np.array(img_resized).astype(np.float32) / 255.0  # Normalize to [0, 1]
    img_np = img_np.transpose(2, 0, 1)  # Change from HWC to CHW
    img_np = np.expand_dims(img_np, axis=0)  # Add batch dimension
    return img_np

# --- Post-processing Function ---
def postprocess_output(output, original_image_size, confidence_threshold=0.25, iou_threshold=0.45):
    # output shape is typically (1, num_boxes, 5 + num_classes) for YOLOv8 ONNX
    # or (1, 84, num_boxes) for transposed output from some exports

    # Assuming output is (1, 84, num_detections) from a standard YOLOv8 export
    # where 84 contains [bbox_x, bbox_y, bbox_w, bbox_h, confidence_obj, class_scores...]
    predictions = np.squeeze(output[0]).T # Transpose to get (num_detections, 84)

    # Filter out low confidence detections
    scores = np.max(predictions[:, 4:], axis=1)
    mask = scores > confidence_threshold
    predictions = predictions[mask]
    scores = scores[mask]

    if len(predictions) == 0:
        return []

    boxes = predictions[:, :4]
    class_ids = np.argmax(predictions[:, 4:], axis=1)

    # Convert box format from (center_x, center_y, width, height) to (x1, y1, x2, y2)
    input_w, input_h = IMG_SIZE
    original_w, original_h = original_image_size

    # Scale factor for resizing boxes back to original image dimensions
    scale_x = original_w / input_w
    scale_y = original_h / input_h

    x_center, y_center, box_w, box_h = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]

    x1 = (x_center - box_w / 2) * scale_x
    y1 = (y_center - box_h / 2) * scale_y
    x2 = (x_center + box_w / 2) * scale_x
    y2 = (y_center + box_h / 2) * scale_y

    boxes = np.stack([x1, y1, x2, y2], axis=1)

    # Apply Non-Maximum Suppression (NMS)
    # This part can be tricky without a dedicated NMS function (e.g., from torchvision.ops or custom impl)
    # For simplicity, we'll use a basic NMS logic or assume onnx output might have it if optimized.
    # For a real app, proper NMS will be considered.

    # A very basic NMS placeholder (not optimized for speed or precision)
    indices = []
    if len(boxes) > 0:
        # Sort by confidence scores descending
        order = scores.argsort()[::-1]
        keep = [True] * len(boxes)
        for i in range(len(boxes)):
            idx_i = order[i]
            if not keep[idx_i]:
                continue
            indices.append(idx_i)
            for j in range(i + 1, len(boxes)):
                idx_j = order[j]
                if not keep[idx_j]:
                    continue
                # Calculate IoU
                # intersection
                ix1 = np.maximum(x1[idx_i], x1[idx_j])
                iy1 = np.maximum(y1[idx_i], y1[idx_j])
                ix2 = np.minimum(x2[idx_i], x2[idx_j])
                iy2 = np.minimum(y2[idx_i], y2[idx_j])
                iw = np.maximum(0., ix2 - ix1)
                ih = np.maximum(0., iy2 - iy1)
                intersection_area = iw * ih

                # union
                area_i = (x2[idx_i] - x1[idx_i]) * (y2[idx_i] - y1[idx_i])
                area_j = (x2[idx_j] - x1[idx_j]) * (y2[idx_j] - y1[idx_j])
                union_area = area_i + area_j - intersection_area
                iou = intersection_area / union_area if union_area > 0 else 0

                if iou > iou_threshold:
                    keep[idx_j] = False

    final_detections = []
    for idx in indices:
        box = boxes[idx]
        score = scores[idx]
        class_id = class_ids[idx]
        final_detections.append({
            'box': box.tolist(),
            'score': float(score),
            'class_id': int(class_id),
            'class_name': CLASS_NAMES[int(class_id)]
        })
    return final_detections

# --- Streamlit UI ---
st.set_page_config(page_title="Electronic Schematic Component Detector", layout="wide")
st.title("🔌 Electronic Schematic Component Detector")
st.markdown("Upload an image of an electronic schematic, and the model will detect components.")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    original_size = image.size
    st.image(image, caption='Uploaded Image', use_column_width=True)
    st.write("")

    if st.button("Detect Components"):
        if session is not None:
            st.spinner("Detecting components...")
            input_tensor = preprocess_image(image)

            # Run inference
            input_name = session.get_inputs()[0].name
            output_name = session.get_outputs()[0].name
            outputs = session.run([output_name], {input_name: input_tensor})

            # Post-process and draw detections
            detections = postprocess_output(outputs, original_size)

            if detections:
                img_draw = image.copy()
                draw = ImageDraw.Draw(img_draw)
                font_size = max(10, int(0.02 * min(original_size)))
                try:
                    font = ImageFont.truetype("arial.ttf", font_size)
                except IOError:
                    font = ImageFont.load_default()

                for det in detections:
                    x1, y1, x2, y2 = det['box']
                    label = f"{det['class_name']} {det['score']:.2f}"
                    color = tuple(np.random.randint(0, 255, 3).tolist()) # Random color for each box

                    draw.rectangle([x1, y1, x2, y2], outline=color, width=3)
                    text_width, text_height = draw.textsize(label, font=font)
                    draw.rectangle([x1, y1 - text_height - 4, x1 + text_width + 4, y1], fill=color)
                    draw.text((x1 + 2, y1 - text_height - 2), label, fill="white", font=font)
                st.success(f"Detected {len(detections)} components!")
                st.image(img_draw, caption='Detected Components', use_column_width=True)
            else:
                st.warning("No components detected with the current confidence threshold.")
        else:
            st.error("Model not loaded. Cannot perform detection.")